HR Application/ERP/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^HR/', include('HR.urls')),
]

HR Application/HR/urls.py
from django.conf.urls import url
from . import views

app_name = 'HR'
urlpatterns = [
    url(r'^login/', views.user_login, name='login'),
    url(r'^logout', views.user_logout, name='logout'),
    url(r'^employee_profile/', views.employee_profile, name='employee_profile'),
    url(r'^home/', views.home, name='home'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^employee_leaves/', views.employee_leaves, name='employee_leaves'),
    url(r'^requested_leaves/', views.requested_leaves, name='requested_leaves'),
    url(r'^about/', views.about, name='about'),
    url(r'^display_leaves/', views.display_leaves, name='display_leaves'),
]

HR Application/HR/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    emp = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    dob = models.DateField()
    sex = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    marital_status = models.CharField(max_length=30)
    contact = models.IntegerField()
    joining_date = models.DateField()
    position = models.CharField(max_length=100)
    emp_status = models.CharField(max_length=70)
    salary = models.CharField(max_length=30)
    bank_name = models.CharField(max_length=100)
    bank_account = models.IntegerField()
    skill_set = models.TextField()
    image = models.ImageField(upload_to='HR/static/HR')

    def __str__(self):
        return self.name


class RequestedLeaves(models.Model):
    requestedLeaves = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.TextField()
    date_time = models.DateTimeField()
    requestedLeaves_text = models.TextField()
    whyLeaves = models.CharField(max_length=50)
    choice = (('0', 'Pending'), ('1', 'Resolved'))
    status = models.CharField(max_length=10, choices=choice)

    def __str__(self):
        return self.subject

HR Application/HR/views.py
from django.shortcuts import render
from .models import User, Employee, RequestedLeaves
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from datetime import datetime
import dateutil.parser
import pickle
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import matplotlib.pyplot as plt

sid = SentimentIntensityAnalyzer()


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/HR/home/')
            else:
                return HttpResponseRedirect("Account Disabled")
        else:
            print("Invalid credentials: {0}, {1}".format(username, password))
            return HttpResponseRedirect("Invalid login credentials")
    else:
        return render(request, 'HR/login.html', {})


@login_required(redirect_field_name='/HR/login/')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/HR/home/')


def home(request):
    context = {}
    return render(request, 'HR/home.html', context)


def employee_profile(request):
    context = {}
    try:
        user = User.objects.get(username=request.user.username)
        emp = Employee.objects.get(emp=user)
        context["emp"] = emp
    except:
        pass
    return render(request, 'HR/employee_profile.html', context)



def employee_leaves(request):
    context = {}
    if request.method == 'POST':

        try:
            user = User.objects.get(username=request.user.username)
            emp = Employee.objects.get(emp=user)
            dt = dateutil.parser.parse(datetime.now().strftime("%m/%d/%y %H:%M:%S"))
            leave = RequestedLeaves(id=None, subject=request.POST.get('subject'), requestedLeaves_text=request.POST.get('text'), date_time=dt,  whyLeaves=emp.name, requestedLeaves=user)
            leave.save()
        except:
            pass

    return render(request, 'HR/employee_leaves.html', context)


def dashboard(request):
    context = {}
    profiles = []
    user = User.objects.get(username=request.user.username)
    if user.is_superuser:
        employees = Employee.objects.all()
        for emp in employees:
            profiles.append(emp)
    context["profiles"] = profiles
    return render(request, 'HR/dashboard.html', context)


def requested_leaves(request):
    context = {}
    comp = []
    user = User.objects.get(username=request.user.username)
    if user.is_superuser:
        requestedLeaves = RequestedLeaves.objects.all()
        for i in requestedLeaves:
            comp.append(i)
    else:
        requestedLeaves = RequestedLeaves.objects.filter(requestedLeaves=user)
        for i in requestedLeaves:
            comp.append(i)
    context['leaves'] = comp

    return render(request, 'HR/leaves.html', context)

def display_leaves(request):
    context = {}
    comp = []
    user = User.objects.get(username=request.user.username)
    if user.is_superuser:
        requestedLeaves = RequestedLeaves.objects.all()
        for i in requestedLeaves:
            comp.append(i)
    else:
        requestedLeaves = RequestedLeaves.objects.filter(requestedLeaves=user)
        for i in requestedLeaves:
            comp.append(i)
    context['leaves'] = comp

    return render(request, 'HR/display_myleaves.html', context)

def pie_chart(reviews, label):

    fig = plt.figure()
    plt.pie(reviews, labels=label, explode=(0.05, 0.05, 0.05, 0.05, 0.05), autopct='%1.1f%%', shadow=True, startangle=140)
    plt.axis('equal')
    fig.savefig("/home/mayank/ERP/HR/static/HR/graph.png")
    plt.close(fig)


def about(request):
    context = {}
    try:
        user = User.objects.get(username=request.user.username)
        emp = Employee.objects.get(emp=user)
        context["emp"] = emp
    except:
        pass
    return render(request, 'HR/about.html', context)

HR Application/HR/templates/HR/about.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
     <title>Fighters' HR Management System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Soft Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"/>
     <link href="{% static 'HR/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'HR/style.css' %}" rel="stylesheet" type="text/css" media="all"/>

    <!-- //for bootstrap working -->
    <link href="//fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic'
          rel='stylesheet' type='text/css'>
     <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <style>
    .inner_page_agile {
	text-align: center;
	background: url({% static 'HR/backimage2.jpg' %}) no-repeat 0px 0px;
	background-size: cover;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	-ms-background-size: cover;
	min-height: 255px;
	padding-top: 6em;
    }
    </style>
</head>
<body>
<div class="header" id="home">
    <div class="content white agile-info">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'HR:home' %}">
                        <h1><span class="far fa-compass" aria-hidden="true"></span> Fighters' HR <label style="color:red">Management System</label>
                        </h1>
                    </a>
                </div>
                <!--/.navbar-header-->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <nav class="link-effect-2" id="link-effect-2">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'HR:home' %}" class="effect-3">Home</a></li>
                            {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                             <li class="dropdown">
                                <a href="#" class="dropdown-toggle effect-3" data-toggle="dropdown">Admin<b
                                        class="caret"></b></a>
                                <ul class="dropdown-menu multi-column columns-2">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <ul class="multi-column-dropdown">

                                                <li><a href="{% url 'HR:dashboard' %}">Dashboard</a></li>
                                                <li class="divider"></li>
                                                <li><a href="{% url 'HR:requested_leaves' %}">Leaves of absence</a></li>
                                                <li class="divider"></li>


                                            </ul>
                                        </div>

                                    </div>
                                </ul>
                            </li>
                            {% else %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle effect-3" data-toggle="dropdown">Employee <b
                                        class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'HR:employee_profile' %}">Employee Profile</a></li>
                                    <li class="divider"></li>
                                    <li><a href="{% url 'HR:employee_leaves' %}">Request a leave</a></li>
                                    <li class="divider"></li>



                                </ul>
                            </li>
                            {% endif %}{% endif %}


                            <li class="active"><a href="{% url 'HR:about' %}"  class="effect-3">About us</a></li>

                            {% if user.is_authenticated %}
                            <li><a href="{% url 'HR:logout' %}" class="effect-3">Log Out</a></li>
                            {% else %}
                            <li><a href="{% url 'HR:login' %}" class="effect-3">Log In</a></li>
                            {% endif %}


                        </ul>
                    </nav>
                </div>
                <!--/.navbar-collapse-->
                <!--/.navbar-->
            </div>
        </nav>
    </div>
</div>
<!-- banner -->
	<div class="inner_page_agile">
		<h3 style="color:white">About us</h3>


	</div>
	<!--//banner -->
	<!--/w3_short-->
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">

			<ul class="short_w3ls"_w3ls>
				<li><a href="{% url 'HR:home' %}">Home</a><span>|</span></li>
				<li>About Us</li>
			</ul>
		</div>
	</div>
	<!--//w3_short-->
	<!-- /inner_content -->
	<div class="inner_content_info_agileits">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle">Employees' Profiles</h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-8 job_info_left">

					<div class="tab_grid_prof">

						<div class="col-sm-3 loc_1">
							<a href="single.html"><img src="{{MEDIA_URL}}{{emp.image.url}}" alt=""></a>
						</div>
						<div class="col-sm-9">
							<div class="location_box1">
								<h6>{{emp.name}}</h6>
								<span class="m_2_prof">{{emp.position}}</span>
								<div class="person-info">
									<ul>

										<li><span>Gender</span>: {{emp.sex}}</li>
										<li><span>Location</span>: {{emp.address}}</li>
										<li><span>Section</span>: {{emp.emp_status}}</li>
										<li><span>Skill set</span>: {{emp.skill_set}}</li>
									</ul>
								</div>

							</div>
						</div>
						<div class="clearfix"> </div>
					</div>
					<ul class="pagination paging w3-agileits-paging">
						<li>
							<a href="#" aria-label="TOP">TOP
						<span aria-hidden="true"></span>
					  </a>

					</ul>
				</div>

					</div>


		</div>
	</div>
	</div>

<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                 <div class="footer_bottom1">
                    <a href="{% url 'HR:home' %}">
                        <h2><span class="far fa-compass" aria-hidden="true"></span> Fighters' HR  <label style="color:red"> MANAGEMENT SYSTEM</label>
                        </h2>
                    </a>
                    <p>© 2021| All rights reserved | Team Fighters<a href="http://w3layouts.com"></a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                        <li><a href="https://www.facebook.com/"><i class="fab fa-facebook fa-2x"></i></a></li>
                        <li><a href="https://twitter.com/"><i class="fab fa-twitter fa-2x"></i></a></li>
						  <li><a href="https://linkedin.com/"><i class="fab fa-linkedin fa-2x"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover"
                                                                         style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="{% static 'HR/jquery-2.1.4.min.js' %}"></script>

<script type="text/javascript" src="{% static 'HR/bootstrap.js' %}"></script>

<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}

</script>
</body>
</html>

HR Application/HR/templates/HR/employee_leaves.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <title>Fighters' HR Management System</title>
    <!--/tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Soft Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"/>

    <!--//tags -->
    <link href="{% static 'HR/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'HR/style.css' %}" rel="stylesheet" type="text/css" media="all"/>

    <!-- //for bootstrap working -->
    <link href="//fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic'
          rel='stylesheet' type='text/css'>
     <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <style>
    .inner_page_agile {
	text-align: center;
	background: url({% static 'HR/backimage.jpg' %}) no-repeat 0px 0px;
	background-size: cover;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	-ms-background-size: cover;
	min-height: 255px;
	padding-top: 6em;
    }
    </style>
</head>

<body>
<!-- header -->
<div class="header" id="home">
    <div class="content white agile-info">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'HR:home' %}">
                       <h1><span class="far fa-compass" aria-hidden="true"></span> Fighters' HR <label style="color:red">Management System</label>
                        </h1>
                    </a>
                </div>
                <!--/.navbar-header-->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <nav class="link-effect-2" id="link-effect-2">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'HR:home' %}" class="effect-3">Home</a></li>
                            {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                             <li class="dropdown">
                                <a href="#" class="dropdown-toggle effect-3" data-toggle="dropdown">Admin<b
                                        class="caret"></b></a>
                                <ul class="dropdown-menu multi-column columns-2">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <ul class="multi-column-dropdown">

                                                <li><a href="{% url 'HR:dashboard' %}">Dashboard</a></li>
                                                <li class="divider"></li>
                                                <li><a href="{% url 'HR:requested_leaves' %}">Leaves of absence</a></li>
                                                <li class="divider"></li>


                                            </ul>
                                        </div>

                                    </div>
                                </ul>
                            </li>
                            {% else %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle effect-3" data-toggle="dropdown">Employee <b
                                        class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'HR:employee_profile' %}">Employee Profile</a></li>
                                    <li class="divider"></li>
                                    <li  class="active"><a href="{% url 'HR:employee_leaves' %}">Request a leave</a></li>
                                    <li class="divider"></li>



                                </ul>
                            </li>
                            {% endif %}{% endif %}


                            <li><a href="{% url 'HR:about' %}" class="effect-3">About us</a></li>

                            {% if user.is_authenticated %}
                            <li><a href="{% url 'HR:logout' %}" class="effect-3">Log Out</a></li>
                            {% else %}
                            <li><a href="{% url 'HR:login' %}" class="effect-3">Log In</a></li>
                            {% endif %}


                        </ul>
                    </nav>
                </div>
                <!--/.navbar-collapse-->
                <!--/.navbar-->
            </div>
        </nav>
    </div>
</div>

<div class="inner_page_agile">
		<h3>Leave Submission</h3>

	</div>
	<!--//banner -->
	<!--/w3_short-->
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">

			<ul class="short_w3ls">
				<li><a href="{% url 'HR:home' %}">Home</a><span>|</span></li>
				<li>Request a leave<span>|</span></li>
                <li><a href="{% url 'HR:display_leaves' %}">My Recieved leaves</a></li>
			</ul>
		</div>
	</div>
	<!--//w3_short-->
	<!-- /inner_content -->
	<div class="inner_content_info_agileits">
		<div class="container">
			<div class="inner_sec_grids_info_w3ls">
				<div class="clearfix"> </div>
				<div class="col-md-8 wthree_contact_center_grid"><h3>Tell us about your reason and request for a leave.</h3></div>
				<div class="w3layouts_mail_grid">
                    <div class="col-md-6-offset-3 wthree_contact_left_grid">
                        <form action="HR/employee_complaints/" method="post">{% csrf_token %}
							<input type="text" name="subject" placeholder="Subject" required=""/>
							<input type="text" name="text" placeholder="Enter you reasons of requesting leaves here...." required="" style="height:100px"/>
							<input type="submit" name="Submit"/>
						</form>
                    </div>

                    <ul class="pagination paging w3-agileits-paging">
						<li>
							<a href="#" aria-label="TOP">TOP
						<span aria-hidden="true"></span>
					  </a>

					</ul>
				</div>


			</div>

		</div>
	</div>


<!--Footer-->
<div class="footer_w3ls">
    <div class="container">
        <div class="footer_bottom">
            <div class="col-md-9 footer_bottom_grid">
                 <div class="footer_bottom1">
                    <a href="{% url 'HR:home' %}">
                        <h2><span class="far fa-compass" aria-hidden="true"></span> Fighters' HR  <label style="color:red"> MANAGEMENT SYSTEM</label>
                        </h2>
                    </a>
                    <p>© 2021| All rights reserved | Team Fighters<a href="http://w3layouts.com"></a></p>
                </div>
            </div>
            <div class="col-md-3 footer_bottom_grid">
                <h6>Follow Us</h6>
                <div class="social">
                    <ul>
                            <li><a href="https://www.facebook.com/"><i class="fab fa-facebook fa-2x"></i></a></li>
                        <li><a href="https://twitter.com/"><i class="fab fa-twitter fa-2x"></i></a></li>
						  <li><a href="https://linkedin.com/"><i class="fab fa-linkedin fa-2x"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>

    </div>
</div>
<!-- //footer -->

<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover"
                                                                         style="opacity: 1;"> </span></a>
<!-- js -->
<script type="text/javascript" src="{% static 'HR/jquery-2.1.4.min.js' %}"></script>

<script type="text/javascript" src="{% static 'HR/bootstrap.js' %}"></script>

<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}

</script>
</body>

</html>